# Generated by Django 3.0.5 on 2020-04-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('renk', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('kilometre', models.IntegerField()),
                ('vites', models.CharField(choices=[('yarıoto', 'Yarı Otomatik'), ('tamoto', 'Tam Otomatik'), ('manuel', 'Manuel')], default='Belirtilmedi', max_length=20)),
                ('durum', models.CharField(choices=[('sıfır', 'Sıfır'), ('ikinciel', 'İkinci El')], default='Belirtilmedi', max_length=20)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
    ]
